# Generated by Django 4.1.2 on 2022-10-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='student', max_length=50, unique=True, verbose_name='name'),
        ),
    ]
