# Generated by Django 4.1.2 on 2022-10-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_name'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, to='user.student', to_field='name', verbose_name='student'),
        ),
    ]
